export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const LOAD_ALL_PAYMENT_SYSTEMS = 'LOAD_ALL_PAYMENT_SYSTEMS'
export const TOGGLE_ACTIVE_CRYPTO = 'TOGGLE_ACTIVE_CRYPTO'
export const LOAD_CRYPTO_PAIR = 'LOAD_CRYPTO_PAIR'
export const SET_AMOUNT_CRYPTO = 'SET_AMOUNT_CRYPTO'
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const REDIRECT_TO_TRANSACTION_FINISHED = 'REDIRECT_TO_TRANSACTION_FINISHED'
export const GET_TRANSACTION_STATUS = 'GET_TRANSACTION_STATUS'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'